package me.vinceh121.jskolengo.entities;

public enum Operation {
	READ_EVALUATIONS,
	READ_HOMEWORK_ASSIGNMENTS,
	MARK_HOMEWORK_ASSIGNMENT_AS_DONE,
	READ_LESSONS,
	READ_ABSENCE_FILES,
	READ_MESSAGES,
	WRITE_MESSAGES;
}
